### ISSUE TITLE
Shutter state stuck in both touchwand app and apple Homekit

### ISSUE THREAD

**Issue by elikapiiro** [ranmee/homebridge-ifeel-shutters#11]
Both of my apps(touchwand / apple Homekit) show Shutters on 12% or 9% open when they are fully closed and this makes them not usable anymore.

some of my shutters are completely stuck now.

**Comment by ranmee** [comment]
Hi @elikapiiro, this is unrelated to my Homebridge add-on but to the i-feel controls you have installed in your shutters. I suggest talking with them to resolve this.
